Add Restream Support
vapor-community/Imperial pull request #104
Opened 2024-07-27 12:56 UTC by vamsii777

This PR adds support for Restream OAuth integration to the Imperial package.

Depends on 
- #100

2024-07-27 14:42 UTC, fpseverino commented
You can remove the `Tests/LinuxMain.swift` file, as it is no longer needed. Also, I think you could use the Vapor CI workflow, like the one I added to [PassKit](https://github.com/vapor-community/PassKit/blob/main/.github/workflows/test.yml).

2024-07-27 14:55 UTC, fpseverino requested changes
In addition to the testing and CI fix, you could update JWTKit to v5, although it may bring breaking changes.

2024-07-27 14:55 UTC, fpseverino commented on Sources/ImperialCore/Routing/FederatedServiceRouter.swift
> +        router.get(callbackURL.pathComponents, use: self.callback)
```suggestion
        router.get(callbackURL.pathComponents, use: { try await self.callback($0) })
```
This is to remove a Sendable warning

2024-07-27 15:34 UTC, vamsii777 commented
@fpseverino, Thanks for the feedback. Given that the current PR focuses on adding a new auth provider, it might be better to handle JWT updates in a separate PR. This will keep our changes focused and easier to review. 

I'll create a new PR for updating JWTKit to v5 and address any potential breaking changes.

2024-07-27 16:10 UTC, fpseverino requested changes

2024-07-27 16:10 UTC, fpseverino commented on Sources/Imperial/Services/Microsoft/MicrosoftRouter.swift
> +        completion: @escaping (Request, String) assync throws -> Response
```suggestion
        completion: @escaping (Request, String) async throws -> Response
```

2024-07-31 11:38 UTC, 0xTim commented
Just an FYI I'm going to be doing an Imperial code sprint next week to go through all the issues and PRs

2024-09-15 21:39 UTC, closed without merging