async/await
vapor-community/Imperial pull request #94
Opened 2023-10-12 14:14 UTC by proggeramlug

Not perfect but a starting point. Also definitely not tested for all providers.

I need this for Twitter/X and so I thought I'll bite the bullet and make it async/await.

2023-10-26 02:05 UTC, chibombo requested changes

2023-10-26 02:05 UTC, chibombo commented on Sources/ImperialGitHub/GitHubRouter.swift
> +    public required init(callback: String, completion: @escaping (Vapor.Request, String) async throws -> Vapor.Response) async throws {
I guess we don't need to add the `Vapor.` declaration, Should we keep it?

2023-11-20 12:34 UTC, 0xTim commented on Sources/ImperialCore/Routing/FederatedServiceRouter.swift
> +    func callback(_ request: Request) async throws -> Response
`@Sendable` should not be added to function declarations - it's a half broken implementation that currently just disables sendable checking inside that function. We should definitely enable Sendable checking on the library though

2024-03-11 12:58 UTC, wibed commented
any update?

2024-07-31 11:39 UTC, 0xTim commented
Just an FYI I'm going to be doing an Imperial code sprint next week to go through all the issues and PRs

2024-07-31 14:35 UTC, bwdmr commented
i did a small rewrite, in which i applied the pattern of the jwt-kit and layered oauth on top of it.
if youd like to have a look:
https://github.com/bwdmr/oauth-kit

2024-12-12 23:41 UTC, 0xTim commented
Closing in favour of https://github.com/vapor-community/Imperial/pull/109

2024-12-12 23:41 UTC, closed without merging